name = "flywheelultimate-com"
main = "src/index.ts"
compatibility_date = "2024-08-31"
workers_dev = true

routes = [
	{ pattern = "flywheelultimate.com", custom_domain = true },
	{ pattern = "www.flywheelultimate.com", custom_domain = true }
]
